# Generated by Django 6.0.4 on 2026-04-23 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('payment_process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.paymentprocess')),
            ],
        ),
    ]
