# Generated by Django 6.0.4 on 2026-04-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'payment processes',
            },
        ),
    ]
