"""
Create the partitioned ``workflows_workflowstep`` table and the initial set
of monthly child partitions.

Django's schema editor cannot emit ``PARTITION BY RANGE (...)``, so this
runs as raw SQL. The ``WorkflowStep`` model is ``managed = False`` — no
state_operations needed because the autodetector already ignores it.
"""

from django.db import migrations


PARENT_TABLE_SQL = """
CREATE TABLE workflows_workflowstep (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    workflow_id BIGINT      NOT NULL,
    name        VARCHAR(100) NOT NULL,
    status      VARCHAR(20) NOT NULL,
    payload     JSONB       NOT NULL DEFAULT '{}',
    created_at  TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    -- Partition key (created_at) MUST be part of every unique constraint
    -- on a partitioned table. A plain PRIMARY KEY(id) is rejected by PG.
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

-- Indexes on the parent get propagated to every current and future
-- partition automatically. Partitioning by created_at means range
-- scans within a month hit a single partition; the workflow_id index
-- still works globally across partitions.
CREATE INDEX ON workflows_workflowstep (workflow_id);
CREATE INDEX ON workflows_workflowstep (status);
"""

# Monthly partitions covering a ~9 month window around the demo's "today"
# (2026-04-16). Add more with the `add_partition` management command.
PARTITION_MONTHS = [
    ("2025_11", "2025-11-01", "2025-12-01"),
    ("2025_12", "2025-12-01", "2026-01-01"),
    ("2026_01", "2026-01-01", "2026-02-01"),
    ("2026_02", "2026-02-01", "2026-03-01"),
    ("2026_03", "2026-03-01", "2026-04-01"),
    ("2026_04", "2026-04-01", "2026-05-01"),
    ("2026_05", "2026-05-01", "2026-06-01"),
]


def _partition_sql() -> str:
    stmts = []
    for suffix, lo, hi in PARTITION_MONTHS:
        stmts.append(
            f"CREATE TABLE workflows_workflowstep_{suffix} "
            f"PARTITION OF workflows_workflowstep "
            f"FOR VALUES FROM ('{lo}') TO ('{hi}');"
        )
    # Safety net for rows that don't match any defined range. In
    # production you'd monitor this and avoid it — rows in DEFAULT
    # block attaching a new partition covering the same range.
    stmts.append(
        "CREATE TABLE workflows_workflowstep_default "
        "PARTITION OF workflows_workflowstep DEFAULT;"
    )
    return "\n".join(stmts)


REVERSE_SQL = "DROP TABLE IF EXISTS workflows_workflowstep CASCADE;"


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.RunSQL(
            sql=PARENT_TABLE_SQL + "\n" + _partition_sql(),
            reverse_sql=REVERSE_SQL,
        ),
    ]
