# Generated by Django 6.0.4 on 2026-04-22 23:31

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('url', models.URLField(max_length=2048)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(models.Func(models.F('url'), function='SUBSTRING', template="%(function)s(%(expressions)s from '.*://([^/]*)')"), name='shortener_shorturl_domain_fix'), models.Index(condition=models.Q(('hits', 0)), fields=['id'], name='shortener_shorturl_unused_pix'), django.contrib.postgres.indexes.HashIndex(fields=['url'], name='shortener_shorturl_url_hix'), django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='shortener_shorturl_created_bix', pages_per_range=4)],
                'constraints': [models.UniqueConstraint(fields=('key',), include=('url',), name='shortener_shorturl_key_uk')],
            },
        ),
    ]
